config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: "users/registrations", confirmations: "users/confirmations" }

  resources :books, only: [:show, :index]

  resources :orders, only: [:show, :index, :edit] do
    member do
      post "place", to: 'orders#place_order'
      post "confirm", to: 'orders#confirm_order'
    end
  end

  resources :line_items, only: [:update, :destroy] do
    collection do
      post "add_to_cart", to: 'line_items#add_to_cart', as: :add_to_cart
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :line_items
  has_many :orders, :through => :line_items

  validates :title, :published_date, :author, :price, presence: true
  monetize :price_cents
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :book, :counter_cache => :order_count
  belongs_to :order

  validates :quantity, :book, presence: true

  def price
    book.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items
  belongs_to :user

  attr_accessor :stripe_card_token

  def add_line_item(line_item)
    line_items << line_item
  end

  def total
    line_items.map(&:price).sum
  end

  def completed?
    stripe_token.present?
  end

  def charge_card
    if valid?
      charge = Stripe::Charge.create(
        :amount => total.cents,
        :currency => "usd",
        :customer => user.stripe_customer_token, # obtained with Stripe.js
        :description => "Order ##{id}"
      )
      self.stripe_token = charge.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating charge: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :confirmable

  validates :email, :presence => true, :email => true

  has_many :orders

  attr_accessor :stripe_card_token

  def cart
    if last_order.nil? || last_order.completed?
      orders << Order.new
    end
    last_order
  end

  def save_card
    if valid?
      customer = Stripe::Customer.create(
        :source => stripe_card_token, # obtained with Stripe.js
        :description => "#{email}"
      )
      self.stripe_customer_token = customer.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end

  private
    def last_order
      orders.last
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    order = params[:sort] || 'published_date'
    order = 'order_count' if order == 'popularity'

    @q = Book.order(order).ransack(params[:q])

    @books = @q.result.page params[:page]
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :published_date, :author, :category, :description, :price)
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :set_line_item, only: [:update, :destroy]

  def update
    if @line_item.update(line_item_params)
      redirect_to :back, notice: 'LineItem was successfully updated.'
    else
      render :back
    end
  end
  def destroy
    @line_item.destroy
    redirect_to :back, notice: 'Book was successfully deleted from cart.'
  end

  # PUT /orders/add_to_cart
  def add_to_cart
    li = LineItem.create(line_item_params)
    current_user.cart.add_line_item(li)

    if current_user.cart.save
      redirect_to books_url, notice: 'Book was added to cart.'
    else
      redirect_to book_url(line_item_params[:book_id])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    def line_item_params
      params.require(:line_item).permit(:quantity, :book_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :destroy, :place_order, :confirm_order]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders
  end

  # GET /orders/:id
  # GET /orders/:id.json
  def show
  end


  # GET /orders/:id/edit
  def edit
    if @order.completed?
      redirect_to order_url(@order), alert: 'This order has already been placed, and may not be edited.'
    else
      render :cart
    end
  end

  # PUT /orders/:id/place_order
  def place_order
    if @order.user.stripe_customer_token.nil?
      @order.user.stripe_card_token = params[:user][:stripe_card_token]
      @order.user.save_card
    end
    @order.user.update(user_params)
    render :confirmation
  end

  # PUT /orders/:id/confirm_order
  def confirm_order
    if @order.charge_card
      OrderMailer.order_invoice(current_user,@order).deliver_now
      redirect_to @order, notice: "Your order has been placed!"
    else
      redirect_to @order, alert: "There was an error with placing your order: #{@order.errors.full_messages.to_sentence}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = current_user.orders.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:billing_address, :shipping_address)
    end


    def order_params
      params.require(:order).permit()
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  def after_confirmation_path_for(resource_name, resource)
    root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<p>Sort By: <%= link_to "Most Popular", :sort => "popularity" %></p>

<%= search_form_for @q do |f| %>

  <%= f.label :title_cont, "Search" %>
  <%= f.search_field :title_cont %>

  <%= f.submit %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= link_to "Title", :sort => "title" %></th>
      <th><%= link_to "Published date", :sort => "published_date" %></th>
      <th><%= link_to "Author", :sort => "author" %></th>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr class='row row-book'>
        <td class='col col-title'><%= link_to book.title, book %></td>
        <td class='col col-published_date'><%= book.published_date %></td>
        <td class='col col-author'><%= book.author %></td>
        <td class='col col-category'><%= book.category %></td>
      </tr>
    <% end %>
    <%= paginate @books %>
  </tbody>
</table>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Published date:</strong>
  <%= @book.published_date %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price.format %>
</p>

<%= form_tag add_to_cart_line_items_path, method: "post" do %>
  <%= label_tag 'line_item_quantity', "Quantity" %>
  <%= text_field_tag 'line_item[quantity]', 1, id: 'line_item_quantity' %>
  <%= hidden_field_tag 'line_item[book_id]', @book.id %>
  <%= submit_tag "Add to Cart" %>
<% end %>

<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApprenticeshipBookstoreApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<ul class="hmenu">
  <%= render 'menu/registration_items' %>
  <%= render 'menu/login_items' %>
  <%= render 'menu/cart' %>
</ul>

<%= yield %>

</body>
</html>

app/views/menu/_cart.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to 'Cart', edit_order_path(current_user.cart)%>
  </li>
<% end %>

app/views/menu/_login_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>

app/views/menu/_registration_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

app/views/orders/_order_form.html.erb
<h3>Payment Information</h3>
<%= form_for @order.user, :url => place_order_path, :html => {:id => 'payment_form'}, :method => :post do |f| %>
  <%= render :partial => 'shipping_form_fields', :locals=>{:f=>f} %>
  <%= render :partial => 'payment_form_fields', :locals=>{:f=>f} %>
  <%= submit_tag "Submit Order" %>
<% end %>

app/views/orders/_payment_form_fields.html.erb
<div class="field">
  <%= f.label :billing_address, "Billing Address" %>
  <%= f.text_field :billing_address %>
</div>

<%= f.hidden_field :stripe_card_token %>

<% if @order.user.stripe_customer_token.present? %>
  Credit card has been provided.<br/>
  <%= link_to 'Enter new payment info', '#', :onclick => "$('#payment_fields').show();" %>

  <div id='payment_fields' style='display:none;'>
<% else %>
  <div id='payment_fields'>
<% end %>
  <div class="field">
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_code, "CVV" %>
    <%= text_field_tag :card_code, nil, name: nil %>
  </div>
  <div class="field">
    <%= label_tag :card_month, "Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
  </div>
</div>
<br/><br/>
<div id="stripe_error">
  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
</div>

app/views/orders/_shipping_form_fields.html.erb
<div class="field">
  <%= f.label :shipping_address, "Shipping Address" %><br>
  <%= f.text_field :shipping_address %>
</div>

app/views/orders/_summary_table.html.erb
<table id="order-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @order.line_items.each do |li| %>
      <tr>
        <td><%= link_to li.book.title, li.book %></td>
        <td><%= li.book.price.format %></td>
        <td><%= li.quantity %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><strong>Total:</strong><%= @order.total.format %></td>
      <td></td>
  </tbody>
</table>

app/views/orders/cart.html.erb
<h1>Cart</h1>

<table id="order-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @order.line_items.each do |li| %>
      <tr>
        <td><%= link_to li.book.title, li.book %></td>
        <td><%= li.book.price.format %></td>
        <td><%= form_for(li) do |f| %><%= f.text_field :quantity%><% end %></td>
        <td><%= link_to "X", line_item_path(li), :method => :delete, :confirm => 'Are you sure?', :class => 'delete_btn'%></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><strong>Total:</strong><%= @order.total.format %></td>
      <td></td>
  </tbody>
</table>

<hr />

<%= link_to 'Purchase', @order %> |
<%= link_to 'Back to book list', books_path %>

app/views/orders/confirmation.html.erb
<h1>Order Confirmation</h1>

<%= render 'summary_table' %>

<p>Does this look good?</p>
<br/>
<%= link_to 'Confirm', confirm_order_path(@order), :method => :post %> or
<%= link_to 'No, go back', edit_order_path(@order) %>

app/views/orders/index.html.erb
<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Order</h1>

<%= render 'summary_table' %>

<hr />
<% if @order.completed? %>
  This order has been completed. Your books should arrive soon.
<% else %>
<%= render 'order_form' %>
<% end %>

<hr />

<% if ! @order.completed? %>
<%= link_to 'Edit order', edit_order_path(@order) %> |
<% end %>
<%= link_to 'Back to book list', books_path %>